import HomePage from "@/components/HomePage";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Electric cars, Solar & Clean Energy</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/icon.png' />
      </Head>
      <main>
        <HomePage/>
      </main>
    </>
  );
}
